### PR TITLE
fix: not modify the original version

### PR DESCRIPTION
**Pull request by nikpivkin**
Methods that bump a version modify the original object, which leads to unexpected results when comparing a constraint in a loop:

```go
package main

import (
	"fmt"
	"sort"

	"github.com/aquasecurity/go-version/pkg/version"
)

func main() {
	versionsRaw := []string{"3.0.0", "3.1.0", "3.1.1", "3.1.2", "3.1.3", "3.2.0", "4.0.0"}
	versions := make([]version.Version, len(versionsRaw))
	for i, raw := range versionsRaw {
		v, _ := version.Parse(raw)
		versions[i] = v
	}

	sort.Sort(sort.Reverse(version.Collection(versions)))

	fmt.Println(versions)
	constraints, _ := version.NewConstraints("~> 3.0")
	for _, ver := range versions {
		if constraints.Check(ver) {
			fmt.Println(ver)
			return
		}
	}

	fmt.Println("Not found")
}

```

```
go run .
[4.0.0 3.2.0 3.1.3 3.1.2 3.1.1 3.1.0 3.0.0]
Not found
```

Also from the Trivy logs:
```
Requesting module versions from registry using 'https://registry.terraform.io/v1/modules/terraform-google-modules/kubernetes-engine/google/versions'...
Found version '29.0.0' for constraint '~> 24.0'
```

### CODE REVIEW

**Review by knqyf263 — APPROVED** [review]

**Comment by knqyf263** [comment]
We probably need to bump Go and golangci-lint first.

**Comment by nikpivkin** [comment]
@knqyf263 Should we open a separate PR for this?

**Comment by knqyf263** [comment]
yes, please

**Comment by nikpivkin** [comment]
@knqyf263 I opened PR https://github.com/aquasecurity/go-version/pull/5

**Comment by knqyf263** [comment]
Thanks. Merged #5

**Pull request merged**
